//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Feel.Resources.ResourceLanguage", typeof(ResourceLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento.
        /// </summary>
        public static string Aggiornamento {
            get {
                return ResourceManager.GetString("Aggiornamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimentazione.
        /// </summary>
        public static string Alimentazione {
            get {
                return ResourceManager.GetString("Alimentazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animali.
        /// </summary>
        public static string Animali {
            get {
                return ResourceManager.GetString("Animali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string Annulla {
            get {
                return ResourceManager.GetString("Annulla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arte.
        /// </summary>
        public static string Arte {
            get {
                return ResourceManager.GetString("Arte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attuale.
        /// </summary>
        public static string Attuale {
            get {
                return ResourceManager.GetString("Attuale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci un importo o un valore numerico inerente al tuo obiettivo per avvicinarti o raggiungere il Target..
        /// </summary>
        public static string AvvicinatiTarget {
            get {
                return ResourceManager.GetString("AvvicinatiTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bellezza.
        /// </summary>
        public static string Bellezza {
            get {
                return ResourceManager.GetString("Bellezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benessere.
        /// </summary>
        public static string Benessere {
            get {
                return ResourceManager.GetString("Benessere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casa.
        /// </summary>
        public static string Casa {
            get {
                return ResourceManager.GetString("Casa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check periodico.
        /// </summary>
        public static string CheckPeriodico {
            get {
                return ResourceManager.GetString("CheckPeriodico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        public static string Chiudi {
            get {
                return ResourceManager.GetString("Chiudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao.
        /// </summary>
        public static string Ciao {
            get {
                return ResourceManager.GetString("Ciao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completati.
        /// </summary>
        public static string Completati {
            get {
                return ResourceManager.GetString("Completati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultura.
        /// </summary>
        public static string Cultura {
            get {
                return ResourceManager.GetString("Cultura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ecco i tuoi obiettivi.
        /// </summary>
        public static string DashboardEccoObiettivi {
            get {
                return ResourceManager.GetString("DashboardEccoObiettivi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completato.
        /// </summary>
        public static string DataCompletamento {
            get {
                return ResourceManager.GetString("DataCompletamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione (Opzionale).
        /// </summary>
        public static string Descrizione {
            get {
                return ResourceManager.GetString("Descrizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educazione.
        /// </summary>
        public static string Educazione {
            get {
                return ResourceManager.GetString("Educazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventi.
        /// </summary>
        public static string Eventi {
            get {
                return ResourceManager.GetString("Eventi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famiglia.
        /// </summary>
        public static string Famiglia {
            get {
                return ResourceManager.GetString("Famiglia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtra.
        /// </summary>
        public static string Filtra {
            get {
                return ResourceManager.GetString("Filtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giorni alla scadenza.
        /// </summary>
        public static string GiorniScadenza {
            get {
                return ResourceManager.GetString("GiorniScadenza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilisci se questo obiettivo sarà aggiornato attraverso check periodici. Ad esempio, se il tuo obiettivo è leggere 10 libri, fissa il tuo Target a 10 e spunta Check Periodico così da eseguire un +1 ad ogni check..
        /// </summary>
        public static string InfoCheck {
            get {
                return ResourceManager.GetString("InfoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definisci un valore numerico che vuoi raggiungere in base all&apos;obiettivo prefissato. Ad esempio, se vuoi risparmiare 1.000 euro, il Target che dovrai scrivere sarà 1.000, e quando lo raggiungerai, l&apos;obiettivo sarà classificato come Completato. Se invece vuoi correre 10km ogni giorno per una settimana, fissa il tuo Target a 7 e spunta Check Periodico, così da aggiungere automaticamente un +1 ogni volta che eseguirai un check..
        /// </summary>
        public static string InfoTarget {
            get {
                return ResourceManager.GetString("InfoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizio.
        /// </summary>
        public static string Inizio {
            get {
                return ResourceManager.GetString("Inizio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci una categoria.
        /// </summary>
        public static string InserisciCategoria {
            get {
                return ResourceManager.GetString("InserisciCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci una data di scadenza.
        /// </summary>
        public static string InserisciData {
            get {
                return ResourceManager.GetString("InserisciData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci un target.
        /// </summary>
        public static string InserisciTarget {
            get {
                return ResourceManager.GetString("InserisciTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci un titolo.
        /// </summary>
        public static string InserisciTitolo {
            get {
                return ResourceManager.GetString("InserisciTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci un valore....
        /// </summary>
        public static string InserisciValore {
            get {
                return ResourceManager.GetString("InserisciValore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavoro.
        /// </summary>
        public static string Lavoro {
            get {
                return ResourceManager.GetString("Lavoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mancano.
        /// </summary>
        public static string Mancano {
            get {
                return ResourceManager.GetString("Mancano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massimo 20 caratteri.
        /// </summary>
        public static string MassimoVentiCaratteri {
            get {
                return ResourceManager.GetString("MassimoVentiCaratteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni sull&apos;app.
        /// </summary>
        public static string MessaggioAssistenteAbout {
            get {
                return ResourceManager.GetString("MessaggioAssistenteAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi un obiettivo.
        /// </summary>
        public static string MessaggioAssistenteAggiuntaObiettivo {
            get {
                return ResourceManager.GetString("MessaggioAssistenteAggiuntaObiettivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area utente.
        /// </summary>
        public static string MessaggioAssistenteAreaUtente {
            get {
                return ResourceManager.GetString("MessaggioAssistenteAreaUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia il tema.
        /// </summary>
        public static string MessaggioAssistenteCambiaTema {
            get {
                return ResourceManager.GetString("MessaggioAssistenteCambiaTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moda.
        /// </summary>
        public static string Moda {
            get {
                return ResourceManager.GetString("Moda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musica.
        /// </summary>
        public static string Musica {
            get {
                return ResourceManager.GetString("Musica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natura.
        /// </summary>
        public static string Natura {
            get {
                return ResourceManager.GetString("Natura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Nessuna descrizione disponibile--.
        /// </summary>
        public static string NessunaDescrizione {
            get {
                return ResourceManager.GetString("NessunaDescrizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non completati.
        /// </summary>
        public static string NonCompletati {
            get {
                return ResourceManager.GetString("NonCompletati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obiettivo.
        /// </summary>
        public static string Obiettivo {
            get {
                return ResourceManager.GetString("Obiettivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrivi il tuo obiettivo....
        /// </summary>
        public static string PlaceholderDescrizione {
            get {
                return ResourceManager.GetString("PlaceholderDescrizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dai un titolo al tuo obiettivo....
        /// </summary>
        public static string PlaceholderObiettivo {
            get {
                return ResourceManager.GetString("PlaceholderObiettivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definisci un target....
        /// </summary>
        public static string PlaceholderTarget {
            get {
                return ResourceManager.GetString("PlaceholderTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica.
        /// </summary>
        public static string Politica {
            get {
                return ResourceManager.GetString("Politica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religione.
        /// </summary>
        public static string Religione {
            get {
                return ResourceManager.GetString("Religione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risparmio.
        /// </summary>
        public static string Risparmio {
            get {
                return ResourceManager.GetString("Risparmio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salute.
        /// </summary>
        public static string Salute {
            get {
                return ResourceManager.GetString("Salute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        public static string Salva {
            get {
                return ResourceManager.GetString("Salva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scadenza.
        /// </summary>
        public static string Scadenza {
            get {
                return ResourceManager.GetString("Scadenza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Seleziona--.
        /// </summary>
        public static string Seleziona {
            get {
                return ResourceManager.GetString("Seleziona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spunta la casella.
        /// </summary>
        public static string SpuntaCasella {
            get {
                return ResourceManager.GetString("SpuntaCasella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        public static string Stato {
            get {
                return ResourceManager.GetString("Stato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci un valore maggiore di zero.
        /// </summary>
        public static string TargetMaggioreDiZero {
            get {
                return ResourceManager.GetString("TargetMaggioreDiZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnologia.
        /// </summary>
        public static string Tecnologia {
            get {
                return ResourceManager.GetString("Tecnologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo libero.
        /// </summary>
        public static string TempoLibero {
            get {
                return ResourceManager.GetString("TempoLibero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termine.
        /// </summary>
        public static string TermineObiettivo {
            get {
                return ResourceManager.GetString("TermineObiettivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica aggiornamenti in corso....
        /// </summary>
        public static string VerificaAggiornamenti {
            get {
                return ResourceManager.GetString("VerificaAggiornamenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viaggi.
        /// </summary>
        public static string Viaggi {
            get {
                return ResourceManager.GetString("Viaggi", resourceCulture);
            }
        }
    }
}
